tcp_connector:
  ros__parameters:
    # Порт TCP-сервера для подключения Android-приложения
    port: 2809
    # Максимальное количество одновременных подключений
    connection_count: 2
    # Режим работы: "simulation" | "production"
    operational_mode: "simulation"
